import { Head } from '@inertiajs/react';
import { LogOut, Monitor, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import AppLayout from '../Layouts/AppLayout';
import { useAuth } from '../contexts/AuthContext';

export default function AccountSettings() {
    const auth = useAuth();
    const [sessions, setSessions] = useState([]);
    useEffect(() => { if (auth.ready && !auth.token) window.location.href = '/login'; if (auth.token) auth.api('/auth/sessions').then((body) => setSessions(body.data)).catch(() => {}); }, [auth.ready, auth.token]);
    async function revoke(id) { await auth.api(`/auth/sessions/${id}`, { method: 'DELETE' }); setSessions(sessions.filter((session) => session.id !== id)); }
    return <AppLayout title="Account settings"><Head title="Account settings" /><div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-sapphire-500">Account / security</p><h2 className="text-3xl font-semibold">Account settings</h2><p className="mt-2 text-sm leading-6 text-slate-400">Manage your profile and active access sessions.</p></div><div className="grid gap-6 lg:grid-cols-2"><section className="panel p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-lg bg-sapphire-500/10 text-sapphire-400"><UserRound size={20} /></div><div><h3 className="font-semibold">Profile</h3><p className="mt-1 text-xs text-slate-500">Your client identity</p></div></div><div className="mt-6 space-y-4"><Info label="Name" value={auth.user?.name || 'Loading'} /><Info label="Email" value={auth.user?.email || 'Loading'} /><Info label="Role" value={auth.user?.is_admin ? 'Administrator' : 'Client'} /></div></section><section className="panel p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-lg bg-azure-500/10 text-azure-400"><ShieldCheck size={20} /></div><div><h3 className="font-semibold">Active sessions</h3><p className="mt-1 text-xs text-slate-500">Revoke access from another device</p></div></div><div className="mt-6 space-y-3">{sessions.length ? sessions.map((session) => <div className="flex items-center justify-between rounded-lg border border-slate-800 bg-navy-950 p-3" key={session.id}><div className="flex items-center gap-3"><Monitor size={16} className="text-slate-500" /><div><b className="block text-xs">{session.user_agent || 'Unknown device'}</b><span className="text-[10px] text-slate-500">{session.ip_address || 'Unknown IP'}</span></div></div><button className="text-xs text-rose-300 hover:text-rose-200" onClick={() => revoke(session.id)}>Revoke</button></div>) : <p className="text-sm text-slate-500">No active session records.</p>}</div><button className="button-secondary mt-5 w-full" onClick={auth.logout}><LogOut size={15} /> Sign out</button></section></div></AppLayout>;
}
function Info({ label, value }) { return <div className="flex justify-between border-b border-slate-800 pb-3 text-sm"><span className="text-slate-500">{label}</span><b className="text-slate-200">{value}</b></div>; }
