import { Head } from '@inertiajs/react';
import { Activity, Boxes, CheckCircle2, CircleAlert, CloudCog, Database, FileJson2, HardDrive, KeyRound, Network, ScrollText, Search, ShieldCheck, UserCog, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import AdminLayout from '../Layouts/AdminLayout';
import { useAuth } from '../contexts/AuthContext';

export default function AdminDashboard({ title = 'Infrastructure' }) {
    const auth = useAuth();
    const [data, setData] = useState(null);
    const [error, setError] = useState('');

    useEffect(() => {
        if (!auth.ready) return;
        if (!auth.token) { window.location.href = '/login'; return; }
        auth.api('/admin/overview').then(setData).catch((requestError) => setError(requestError.message));
    }, [auth.ready, auth.token]);

    const content = {
        Infrastructure: <Infrastructure data={data} />,
        Servers: <ServerDirectory />,
        Users: <UserDirectory />,
        'Nodes & allocations': <NodeRegistry data={data} />,
        'Nests & Eggs': <EggEditor />,
        'Application API': <ApiTokens />,
        'Audit logs': <AuditLogs data={data} />,
    }[title] || <Infrastructure data={data} />;

    return <AdminLayout title={title}><Head title={`${title} · ACP`} />{error ? <ErrorPanel message={error} /> : content}</AdminLayout>;
}

function Infrastructure({ data }) {
    const metrics = data ? [['Users', data.metrics.users, Users], ['Servers', data.metrics.servers, Boxes], ['Running', data.metrics.running_servers, Activity], ['Sessions', data.metrics.active_sessions, ShieldCheck]] : [];
    return <><Heading eyebrow="Infrastructure / command center" title="Global host health" description="Platform-wide containers, users, sessions, and Docker integration." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value, Icon]) => <Metric key={label} label={label} value={value} Icon={Icon} />)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Local node health" icon={<HardDrive size={18} />}><Info label="Status" value={data?.node?.status || 'Loading'} good /><Info label="Socket" value={data?.node?.socket || '/var/run/docker.sock'} /><Info label="Driver" value={data?.node?.driver || 'docker-engine'} /></Panel><Panel title="Container density" icon={<CloudCog size={18} />}><div className="grid grid-cols-3 gap-3 text-center"><Gauge label="Running" value={data?.metrics?.running_servers || 0} /><Gauge label="Stopped" value={Math.max((data?.metrics?.servers || 0) - (data?.metrics?.running_servers || 0), 0)} /><Gauge label="Health" value={data?.node?.reachable ? 100 : 0} suffix="%" /></div></Panel></div></>;
}
function ServerDirectory() { const [query, setQuery] = useState(''); const servers = []; const filtered = servers.filter((server) => `${server.name} ${server.owner}`.toLowerCase().includes(query.toLowerCase())); return <><Heading eyebrow="Global infrastructure" title="Server directory" description="Manage every provisioned game server on the local node." action="Provision server" /><Panel title="Master directory" icon={<Boxes size={18} />}><div className="mb-4 flex items-center gap-2"><Search size={15} className="text-slate-500" /><input className="field max-w-sm" placeholder="Search servers or owners" value={query} onChange={(event) => setQuery(event.target.value)} /></div>{filtered.length ? <Table headers={['Server', 'Owner', 'Status', 'Node', 'Action']} rows={filtered.map((server) => [server.name, server.owner, server.status, server.node, <button className="text-xs text-azure-400">Suspend</button>])} /> : <EmptyState icon={<Boxes size={20} />} text="No servers have been provisioned." />}</Panel></>; }
function UserDirectory() { const users = []; return <><Heading eyebrow="Identity / security" title="User administration" description="Review accounts, roles, sessions, and security posture." action="Create user" /><Panel title="Account directory" icon={<UserCog size={18} />}>{users.length ? <Table headers={['Account', 'Email', 'Role', '2FA', 'Action']} rows={users.map((user) => [user.name, user.email, <Badge>{user.role}</Badge>, user.twoFactor, <button className="text-xs text-azure-400">Manage</button>])} /> : <EmptyState icon={<Users size={20} />} text="No client users have been created." />}</Panel></>; }
function NodeRegistry({ data }) { return <><Heading eyebrow="Infrastructure / local node" title="Nodes & allocations" description="Docker bridge settings and external port registry." action="Generate allocations" /><div className="grid gap-6 lg:grid-cols-2"><Panel title="Inbuilt daemon" icon={<CloudCog size={18} />}><Info label="Socket" value={data?.node?.socket || '/var/run/docker.sock'} /><Info label="Volume root" value="/var/lib/pterodactyl/volumes" /><Info label="Memory over-allocation" value="100%" /><Info label="Disk over-allocation" value="100%" /></Panel><Panel title="Allocation registry" icon={<Network size={18} />}><Table headers={['IP', 'Port', 'Status']} rows={[['0.0.0.0', '25565', <Badge>Assigned</Badge>], ['0.0.0.0', '25566', <Badge tone="green">Available</Badge>], ['0.0.0.0', '25567', <Badge tone="green">Available</Badge>]]} /></Panel></div></>; }
function EggEditor() { const [schema, setSchema] = useState('{\n  "name": "Paper Minecraft",\n  "docker_images": ["java21"],\n  "startup": "java -Xmx{{SERVER_MEMORY}}M -jar server.jar"\n}'); return <><Heading eyebrow="Configuration engine" title="Nests & Eggs" description="Edit game schemas, Docker images, and startup templates." action="Import schema" /><Panel title="Egg schema editor" icon={<FileJson2 size={18} />}><textarea className="min-h-72 w-full rounded-lg border border-slate-700 bg-navy-950 p-4 font-mono text-sm text-azure-400 outline-none focus:border-azure-500" value={schema} onChange={(event) => setSchema(event.target.value)} /><div className="mt-4 flex justify-end"><button className="button-primary">Save schema</button></div></Panel></>; }
function ApiTokens() { const [created, setCreated] = useState(false); return <><Heading eyebrow="Automation / integrations" title="Application API" description="Scoped credentials for WHMCS and infrastructure automation." action="Generate token" /><Panel title="Token provisioning" icon={<KeyRound size={18} />}><div className="flex items-center justify-between rounded-lg border border-slate-800 bg-navy-950 p-4"><div><b>WHMCS provisioning token</b><p className="mt-1 text-xs text-slate-500">servers:read · servers:write · users:read</p></div><button onClick={() => setCreated(true)} className="button-primary">{created ? 'Token generated' : 'Generate'}</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{['Read servers', 'Write servers', 'Manage users', 'Manage allocations'].map((scope) => <label className="flex items-center gap-2 text-sm text-slate-300" key={scope}><input type="checkbox" defaultChecked={scope.includes('servers')} />{scope}</label>)}</div></Panel></>; }
function AuditLogs({ data }) { const logs = data?.recent_activity || []; return <><Heading eyebrow="Security / forensics" title="Audit logs" description="Immutable platform event stream with actor and source details." /><Panel title="Global event stream" icon={<ScrollText size={18} />}><Table headers={['Event', 'Actor', 'IP address', 'Timestamp']} rows={(logs.length ? logs : [{ action: 'No events recorded', actor_user_id: '-', ip_address: '-', created_at: '-' }]).map((item) => [item.action, item.actor_user_id, item.ip_address, item.created_at])} /></Panel></>; }
function Heading({ eyebrow, title, description, action }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-azure-500">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight">{title}</h2><p className="mt-2 text-sm text-slate-400">{description}</p></div>{action && <button className="button-primary">{action}</button>}</div>; }
function Panel({ title, icon, children }) { return <section className="panel p-5"><div className="mb-5 flex items-center gap-3"><div className="rounded-lg bg-azure-500/10 p-2 text-azure-500">{icon}</div><h3 className="font-semibold">{title}</h3></div>{children}</section>; }
function Metric({ label, value, Icon }) { return <div className="rounded-xl border border-teal-500/20 bg-navy-900 p-5"><div className="flex justify-between text-sm text-slate-400"><span>{label}</span><Icon size={18} className="text-azure-500" /></div><strong className="mt-5 block text-3xl">{value}</strong><span className="mt-1 block text-xs text-slate-500">Platform-wide</span></div>; }
function Gauge({ label, value, suffix = '' }) { return <div><div className="mx-auto grid h-20 w-20 place-items-center rounded-full border-4 border-azure-500/30 text-xl font-semibold text-azure-400">{value}{suffix}</div><span className="mt-2 block text-xs text-slate-500">{label}</span></div>; }
function Info({ label, value, good }) { return <div className="flex justify-between border-b border-slate-800 py-3 text-sm"><span className="text-slate-400">{label}</span><b className={good ? 'text-azure-400' : 'text-white'}>{value}</b></div>; }
function Badge({ children, tone = 'blue' }) { return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] ${tone === 'green' ? 'bg-emerald-500/10 text-emerald-300' : 'bg-sapphire-500/10 text-sapphire-300'}`}>{children}</span>; }
function Table({ headers, rows }) { return <div className="overflow-x-auto"><table className="data-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function ErrorPanel({ message }) { return <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-5 text-sm text-rose-200"><CircleAlert size={17} className="mb-2" />{message}</div>; }
function EmptyState({ icon, text }) { return <div className="py-10 text-center text-sm text-slate-500"><div className="mx-auto mb-3 grid h-10 w-10 place-items-center rounded-lg bg-slate-800 text-slate-400">{icon}</div>{text}</div>; }
