import { Head } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { FitAddon } from '@xterm/addon-fit';
import { WebglAddon } from '@xterm/addon-webgl';
import { Terminal as XTerm } from '@xterm/xterm';
import Editor from '@monaco-editor/react';
import { Activity, Archive, ArrowDownToLine, Check, ChevronRight, CircleStop, Clipboard, CloudUpload, Code2, Copy, Database, Download, FileArchive, FileCode2, Folder, FolderOpen, Gauge, HardDrive, KeyRound, LayoutGrid, List, Network, Pause, Play, Plus, Power, RefreshCw, RotateCcw, Save, Search, Server, Settings2, Shield, Square, Terminal as TerminalIcon, Trash2, Upload, Users, Wifi, X } from 'lucide-react';
import { useEffectEvent } from 'react';
import AppLayout from '../Layouts/AppLayout';
import LiveConsolePage from './LiveConsolePage';
import { useAuth } from '../contexts/AuthContext';
import '@xterm/xterm/css/xterm.css';

const chartData = Array.from({ length: 12 }, (_, index) => ({ time: `${index * 2}m`, cpu: 24 + (index * 7) % 30, memory: 42 + (index * 3) % 20, disk: 18 + (index * 4) % 25, network: 30 + (index * 5) % 35 }));
const files = ['server.properties', 'eula.txt', 'world', 'plugins', 'logs', 'paper.jar', 'whitelist.json'];

export default function Dashboard({ title = 'Overview', serverId = null, servers = [], node = {} }) {
    const auth = useAuth();
    const [server, setServer] = useState(servers[0] || { id: serverId, name: 'Loading server', uuid: 'local-demo', status: 'offline', memory: 8192, port: 25565 });
    const [toast, setToast] = useState('');
    useEffect(() => { if (auth.ready && !auth.token) window.location.href = '/login'; }, [auth.ready, auth.token]);
    useEffect(() => { if (serverId && auth.token) auth.api(`/servers/${serverId}`).then((body) => setServer(body.data)).catch((error) => setToast(error.message)); }, [serverId, auth.token]);
    useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 2400); return () => clearTimeout(timer); } }, [toast]);

    const page = title.toLowerCase();
    const content = page === 'console' ? <LiveConsolePage server={server} api={auth.api} notify={setToast} />
        : page === 'files' ? <FilesPage notify={setToast} />
        : page === 'databases' ? <DatabasesPage notify={setToast} />
        : page === 'users' ? <UsersPage notify={setToast} />
        : page === 'backups' ? <BackupsPage notify={setToast} />
        : page === 'startup' ? <StartupPage notify={setToast} />
        : page === 'installer' ? <InstallerPage notify={setToast} />
        : page === 'settings' ? <SettingsPage server={server} notify={setToast} />
        : <OverviewPage server={server} node={node} />;

    return <AppLayout title={title} serverId={serverId}><Head title={title} />{content}{toast && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-lg border border-azure-500/40 bg-navy-800 px-4 py-3 text-sm text-white shadow-2xl shadow-black/40"><Check size={16} className="text-azure-500" />{toast}</div>}</AppLayout>;
}

function OverviewPage({ server, node }) { return <><PageHeading eyebrow="Client panel / operations" title={server.name || 'Your game servers'} description="A live operational view of your local Docker game instance." action="Start server" /><MetricGrid /><div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><TelemetryCard /><StatusCard node={node} /></div></>; }
function PageHeading({ eyebrow = 'Client panel', title, description, action }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.2em] text-sapphire-500">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight">{title}</h2><p className="mt-2 text-sm text-slate-400">{description}</p></div>{action && <button className="button-primary"><Play size={15} fill="currentColor" />{action}</button>}</div>; }
function MetricGrid() { const metrics = [['CPU load', '31.4%', 'of 400% allocated'], ['Memory', '3.8 GB', 'of 8 GB allocated'], ['Disk usage', '42.7 GB', 'of 100 GB allocated'], ['Players', '12', 'online now']]; return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, detail]) => <div className="panel p-5" key={label}><div className="flex justify-between text-xs text-slate-400"><span>{label}</span><Activity size={16} className="text-azure-400" /></div><strong className="mt-5 block text-2xl">{value}</strong><span className="mt-1 block text-xs text-slate-500">{detail}</span></div>)}</div>; }
function TelemetryCard() { return <section className="panel p-5"><PanelHeader icon={<Activity size={17} />} title="Live telemetry" detail="Updates every 2 seconds via local node" /><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="cpu" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#258eff" stopOpacity=".35" /><stop offset="100%" stopColor="#258eff" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#1b385d" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="time" tick={{ fill: '#7185a6', fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#7185a6', fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#102541', border: '1px solid #285177' }} /><Area type="monotone" dataKey="cpu" stroke="#258eff" fill="url(#cpu)" strokeWidth={2} /><Area type="monotone" dataKey="memory" stroke="#25d2c1" fill="none" strokeWidth={2} /><Area type="monotone" dataKey="disk" stroke="#e7aa51" fill="none" strokeWidth={2} /><Area type="monotone" dataKey="network" stroke="#bd7cff" fill="none" strokeWidth={2} /></AreaChart></ResponsiveContainer></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-400"><Legend color="bg-sapphire-500" label="CPU" /><Legend color="bg-azure-500" label="Memory" /><Legend color="bg-amber-400" label="Disk I/O" /><Legend color="bg-fuchsia-400" label="Network" /></div></section>; }
function StatusCard({ node }) { return <section className="panel p-5"><PanelHeader icon={<Server size={17} />} title="Node status" detail="Inbuilt Docker runtime" /><div className="mt-6 space-y-4 text-sm"><StatusRow label="Docker socket" value={node.reachable ? 'Connected' : 'Unavailable'} good={node.reachable} /><StatusRow label="Driver" value={node.driver || 'docker-engine'} /><StatusRow label="Volume root" value="/var/lib/pterodactyl/volumes" /><StatusRow label="WebSocket" value="Ready" good /></div></section>; }
function StatusRow({ label, value, good }) { return <div className="flex items-center justify-between border-b border-slate-800 pb-3"><span className="text-slate-400">{label}</span><b className={good ? 'text-azure-500' : 'text-white'}>{value}</b></div>; }
function PanelHeader({ icon, title, detail, action }) { return <div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="rounded-lg bg-sapphire-500/10 p-2 text-sapphire-400">{icon}</div><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500">{detail}</p></div></div>{action}</div>; }
function Legend({ color, label }) { return <span className="flex items-center gap-2"><i className={`h-2 w-2 rounded-full ${color}`} />{label}</span>; }

function ConsolePage({ server, api, notify }) { const terminalRef = useRef(null); const terminal = useRef(null); const [command, setCommand] = useState(''); const [history, setHistory] = useState([]); const [historyIndex, setHistoryIndex] = useState(-1); const [power, setPower] = useState('running');
    useEffect(() => { if (!terminalRef.current || terminal.current) return; const instance = new XTerm({ cols: 100, rows: 18, scrollback: 5000, convertEol: true, cursorBlink: true, theme: { background: '#061222', foreground: '#c9daf0', cursor: '#25d2c1' } }); const fit = new FitAddon(); instance.loadAddon(fit); try { instance.loadAddon(new WebglAddon()); } catch (_) {} instance.open(terminalRef.current); fit.fit(); instance.writeln('\x1b[36mTidePanel local node connected\x1b[0m'); instance.writeln(`\x1b[90mContainer: ${server.container_name || 'not provisioned'}\x1b[0m`); instance.writeln('Ready for commands.'); terminal.current = instance; return () => instance.dispose(); }, [server]);
    async function send(value = command) { if (!value.trim()) return; terminal.current?.writeln(`\x1b[94m> ${value}\x1b[0m`); setHistory((items) => [value, ...items].slice(0, 50)); setCommand(''); setHistoryIndex(-1); try { await api(`/servers/${server.id}/command`, { method: 'POST', body: JSON.stringify({ command: value }) }); notify('Command accepted by local node'); } catch (error) { terminal.current?.writeln(`\x1b[31m${error.message}\x1b[0m`); notify(error.message); } }
    function keyDown(event) { if (event.key === 'Enter') { event.preventDefault(); send(); } if (event.key === 'ArrowUp') { event.preventDefault(); const index = Math.min(historyIndex + 1, history.length - 1); setHistoryIndex(index); setCommand(history[index] || ''); } if (event.key === 'ArrowDown') { const index = Math.max(historyIndex - 1, -1); setHistoryIndex(index); setCommand(index < 0 ? '' : history[index]); } }
    return <><PageHeading eyebrow="Client panel / server" title="Console & Overview" description="ANSI terminal, power state, and live resource telemetry." /><div className="mb-5 flex flex-wrap gap-2"><PowerButton label="Start" icon={<Play size={15} />} color="emerald" disabled={power === 'running'} onClick={() => setPower('running')} /><PowerButton label="Restart" icon={<RotateCcw size={15} />} color="amber" onClick={() => { setPower('restarting'); setTimeout(() => setPower('running'), 1000); }} /><PowerButton label="Stop" icon={<Square size={15} />} color="rose" onClick={() => setPower('offline')} /><PowerButton label="Force kill" icon={<CircleStop size={15} />} color="red" onClick={() => setPower('offline')} /></div><div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="panel overflow-hidden p-4"><div className="mb-3 flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-azure-500"><i className="h-2 w-2 animate-pulse rounded-full bg-azure-500" />{power === 'running' ? 'Connected' : power}</span><span className="text-slate-500">5,000 line scrollback / WebGL</span></div><div className="terminal-frame" ref={terminalRef} /><div className="mt-3 flex gap-2"><TerminalIcon size={18} className="mt-2 text-slate-500" /><input className="field flex-1" value={command} onChange={(event) => setCommand(event.target.value)} onKeyDown={keyDown} placeholder="Send a command... Up/Down for history" /><button className="button-primary" onClick={() => send()}>Send</button></div></section><TelemetryCard /></div></>; }
function PowerButton({ label, icon, color, onClick, disabled }) { const colors = { emerald: 'border-emerald-500/30 text-emerald-300', amber: 'border-amber-500/30 text-amber-300', rose: 'border-rose-400/30 text-rose-300', red: 'border-red-500/30 text-red-300' }; return <button disabled={disabled} onClick={onClick} className={`flex items-center gap-2 rounded-lg border bg-navy-900 px-4 py-2 text-xs font-semibold transition hover:bg-navy-800 disabled:cursor-not-allowed disabled:opacity-40 ${colors[color]}`}>{icon}{label}</button>; }

function FilesPage({ notify }) { const [query, setQuery] = useState(''); const [selected, setSelected] = useState([]); const [editor, setEditor] = useState(false); const filtered = files.filter((file) => file.toLowerCase().includes(query.toLowerCase())); return <><PageHeading title="File Manager" description="Explore, upload, archive, and edit server files." action="Upload files" /><div className="panel p-5"><div className="mb-5 flex flex-wrap items-center gap-3"><span className="text-xs text-slate-500">/home/container</span><div className="ml-auto flex items-center gap-2"><div className="search-field"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files" /></div><button className="icon-button"><List size={16} /></button><button className="icon-button"><LayoutGrid size={16} /></button></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((file) => <button key={file} onClick={() => file.endsWith('.properties') || file.endsWith('.json') ? setEditor(true) : setSelected((items) => items.includes(file) ? items.filter((item) => item !== file) : [...items, file])} className={`flex items-center gap-3 rounded-lg border p-4 text-left transition hover:border-sapphire-500 ${selected.includes(file) ? 'border-sapphire-500 bg-sapphire-500/10' : 'border-slate-800 bg-navy-900'}`}><input type="checkbox" checked={selected.includes(file)} readOnly /><span className="text-sapphire-400">{file.includes('.') ? <FileCode2 size={20} /> : <Folder size={20} />}</span><span className="truncate text-sm">{file}</span></button>)}</div>{selected.length > 0 && <div className="mt-5 flex items-center gap-3 rounded-lg border border-sapphire-500/30 bg-sapphire-500/10 p-3 text-xs"><span>{selected.length} selected</span><button onClick={() => notify('Archive queued')} className="button-secondary"><Archive size={14} /> Archive</button><button onClick={() => setSelected([])} className="button-secondary"><Trash2 size={14} /> Delete</button></div>}<div className="mt-6 rounded-xl border border-dashed border-sapphire-500/40 bg-sapphire-500/5 p-8 text-center"><CloudUpload className="mx-auto mb-3 text-sapphire-400" /><p className="text-sm">Drop files here for 5 MB chunked upload</p><p className="mt-1 text-xs text-slate-500">Pause, cancel, and resume uploads safely</p></div></div>{editor && <EditorModal onClose={() => setEditor(false)} notify={notify} />}</>; }
function EditorModal({ onClose, notify }) { const [value, setValue] = useState('{\n  "motd": "Aurora Survival",\n  "max-players": 40\n}'); return <div className="modal-backdrop"><div className="modal-panel max-w-4xl"><div className="mb-4 flex justify-between"><div><h3 className="font-semibold">server.properties editor</h3><p className="text-xs text-slate-500">JSON/YAML/TOML/properties syntax support</p></div><button onClick={onClose}><X size={18} /></button></div><Editor height="430px" defaultLanguage="json" theme="vs-dark" value={value} onChange={(next) => setValue(next || '')} options={{ minimap: { enabled: false }, fontSize: 13, folding: true }} /><div className="mt-4 flex justify-end"><button className="button-primary" onClick={() => { notify('File saved'); onClose(); }}><Save size={14} /> Save</button></div></div></div>; }

function DatabasesPage({ notify }) { const [visible, setVisible] = useState(false); const [dbs, setDbs] = useState([{ name: 's1_main', host: '127.0.0.1', user: 's1_admin', password: '••••••••' }]); return <><PageHeading title="Databases" description="Provision isolated MariaDB credentials and host allowlists." action="Create database" /><section className="panel p-5"><PanelHeader icon={<Database size={17} />} title="Database credentials" detail="Container-scoped users and connection endpoints" action={<button className="button-primary" onClick={() => setDbs([...dbs, { name: `s1_db_${dbs.length + 1}`, host: '%', user: 's1_user', password: '••••••••' }])}><Plus size={14} /> Provision</button>} /><div className="mt-5 overflow-x-auto"><table className="data-table"><thead><tr><th>Name</th><th>Host</th><th>User</th><th>Password</th><th /></tr></thead><tbody>{dbs.map((db) => <tr key={db.name}><td className="font-medium text-white">{db.name}</td><td>{db.host}</td><td>{db.user}</td><td>{visible ? 'generated-32-character-secret' : db.password}</td><td className="flex gap-2"><button onClick={() => setVisible(!visible)} className="icon-button"><KeyRound size={14} /></button><button onClick={() => notify('Connection string copied')} className="icon-button"><Copy size={14} /></button></td></tr>)}</tbody></table></div></section></>; }
function SchedulesPage({ notify }) { const [active, setActive] = useState(true); const [tasks, setTasks] = useState(['Send warning', 'Wait 30 seconds', 'Save world', 'Restart server']); return <><PageHeading title="Schedules" description="Chain cron actions with delays and execution auditing." action="New schedule" /><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="panel p-5"><PanelHeader icon={<RotateCcw size={17} />} title="Nightly maintenance" detail="0 4 * * * · next run in 6 hours" action={<button onClick={() => setActive(!active)} className={`toggle ${active ? 'toggle-on' : ''}`}><i /></button>} /><div className="mt-5 space-y-2">{tasks.map((task, index) => <div draggable onDragEnd={() => setTasks([...tasks.slice(0, index), ...tasks.slice(index + 1), task])} key={task} className="flex items-center gap-3 rounded-lg border border-slate-800 bg-navy-950 p-3 text-sm"><span className="text-slate-600">{index + 1}</span><span>{task}</span><ChevronRight size={14} className="ml-auto text-slate-600" /></div>)}</div><button onClick={() => notify('Schedule saved')} className="button-primary mt-5"><Save size={14} /> Save schedule</button></section><section className="panel p-5"><PanelHeader icon={<Activity size={17} />} title="Execution log" detail="Last 5 executions" /><div className="mt-5 space-y-3">{['Completed · 0s', 'Completed · 41s', 'Failed · exit 1'].map((item) => <div key={item} className="flex items-center justify-between border-b border-slate-800 pb-3 text-xs"><span>{item}</span><span className="text-slate-500">Today</span></div>)}</div></section></div></>; }
function UsersPage({ notify }) { const [invite, setInvite] = useState(false); return <><PageHeading title="Users & Subusers" description="Granular permissions for every operator on this server." action="Invite user" /><section className="panel p-5"><PanelHeader icon={<Users size={17} />} title="Access matrix" detail="Owner-controlled sessions and permissions" /><div className="mt-5 overflow-x-auto"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Console</th><th>Files</th><th>Databases</th><th /></tr></thead><tbody>{[['Alex Morgan', 'Owner', 'Accepted'], ['Maya Chen', 'Operator', 'Accepted'], ['Jordan Lee', 'Viewer', 'Pending']].map(([name, role, status]) => <tr key={name}><td className="font-medium text-white">{name}</td><td><span className="badge">{role}</span></td><td>{status}</td><td><input type="checkbox" defaultChecked={role !== 'Viewer'} /></td><td><input type="checkbox" defaultChecked={role === 'Owner' || role === 'Operator'} /></td><td><input type="checkbox" defaultChecked={role === 'Owner'} /></td><td><button onClick={() => notify(`${name} permissions updated`)} className="text-xs text-sapphire-400">Edit</button></td></tr>)}</tbody></table></div></section></>; }
function BackupsPage({ notify }) { const [locked, setLocked] = useState(false); return <><PageHeading title="Backups" description="Snapshot, lock, download, and restore server volumes." action="Create backup" /><section className="panel p-5"><div className="mb-6 flex items-center justify-between"><div><h3 className="font-semibold">Storage quota</h3><p className="mt-1 text-xs text-slate-500">42.7 GB of 100 GB used</p></div><span className="text-sm text-sapphire-400">42%</span></div><div className="meter"><i style={{ width: '42%' }} /></div><div className="mt-6 overflow-x-auto"><table className="data-table"><thead><tr><th>Archive</th><th>Size</th><th>Status</th><th>Created</th><th>Lock</th><th /></tr></thead><tbody>{[['survival-before-update.tar.gz', '8.4 GB', 'Completed'], ['weekly-world.tar.gz', '6.1 GB', 'Completed'], ['manual-2026-09-14.tar.gz', 'Queued', 'Compressing']].map(([name, size, status]) => <tr key={name}><td className="font-medium text-white">{name}</td><td>{size}</td><td><span className="badge badge-green">{status}</span></td><td>Today, 04:00</td><td><input type="checkbox" checked={locked} onChange={() => setLocked(!locked)} /></td><td><button onClick={() => notify('Download URL copied')} className="icon-button"><Download size={14} /></button></td></tr>)}</tbody></table></div></section></>; }
function NetworkPage({ server, notify }) { return <><PageHeading title="Network & Allocations" description="Map host ports, labels, and primary game listeners." action="Add allocation" /><section className="panel p-5"><PanelHeader icon={<Network size={17} />} title="Port mapping table" detail="External routing to container bindings" /><div className="mt-5 overflow-x-auto"><table className="data-table"><thead><tr><th>IP</th><th>External port</th><th>Container port</th><th>Alias</th><th>Primary</th><th /></tr></thead><tbody>{[['0.0.0.0', server.port || 25565, 25565, 'Game Server'], ['0.0.0.0', 25575, 25575, 'RCON'], ['0.0.0.0', 8123, 8123, 'Dynmap Web']].map(([ip, external, internal, alias], index) => <tr key={internal}><td>{ip}</td><td>{external}</td><td>{internal}</td><td><input className="table-input" defaultValue={alias} /></td><td><input type="radio" name="primary" defaultChecked={index === 0} /></td><td><button onClick={() => { navigator.clipboard?.writeText(`${ip}:${external}`); notify('Allocation copied'); }} className="icon-button"><Copy size={14} /></button></td></tr>)}</tbody></table></div></section></>; }
function StartupPage({ notify }) { const [version, setVersion] = useState('21'); const [heap, setHeap] = useState('6G'); return <><PageHeading title="Startup Parameters" description="Validated Egg variables and live Docker command preview." action="Save variables" /><div className="grid gap-6 lg:grid-cols-2"><section className="panel p-5"><PanelHeader icon={<Settings2 size={17} />} title="Environment variables" detail="PaperMC Egg schema" /><div className="mt-5 space-y-4"><label className="field-label">Java runtime<select className="field" value={version} onChange={(event) => setVersion(event.target.value)}><option value="17">Java 17</option><option value="21">Java 21</option></select></label><label className="field-label">Max heap<input className="field" value={heap} onChange={(event) => setHeap(event.target.value)} pattern="^[0-9]+G$" /></label><label className="field-label">Server jar<input className="field" defaultValue="paper.jar" /></label></div><button onClick={() => notify('Variables saved')} className="button-primary mt-5"><Save size={14} /> Save</button></section><section className="panel p-5"><PanelHeader icon={<Code2 size={17} />} title="Command preview" detail="Read-only resolved startup string" /><pre className="mt-5 overflow-auto rounded-lg border border-slate-800 bg-navy-950 p-4 text-xs leading-6 text-azure-400">docker run --memory 8g<br />  -e JAVA_VERSION={version}<br />  -e MAX_MEMORY={heap}<br />  itzg/minecraft-server:java{version}<br />  java -Xms128M -Xmx{heap} -jar paper.jar nogui</pre></section></div></>; }
function InstallerPage({ notify }) { const [engine, setEngine] = useState('Paper'); const [version, setVersion] = useState('1.21.1'); return <><PageHeading title="1-Click Installer" description="Fetch upstream game engines and deploy operational macros." action="Install build" /><section className="panel p-5"><PanelHeader icon={<Download size={17} />} title="Engine switcher" detail="PaperMC, Purpur, Fabric, Spigot, Velocity" /><div className="mt-5 grid gap-4 sm:grid-cols-3"><select className="field" value={engine} onChange={(event) => setEngine(event.target.value)}>{['Paper', 'Purpur', 'Fabric', 'Spigot', 'Velocity'].map((item) => <option key={item}>{item}</option>)}</select><select className="field" value={version} onChange={(event) => setVersion(event.target.value)}><option>1.21.1</option><option>1.20.6</option><option>1.20.4</option></select><button onClick={() => notify(`${engine} ${version} install queued`)} className="button-primary"><Download size={14} /> Install</button></div></section><section className="panel mt-6 p-5"><PanelHeader icon={<TerminalIcon size={17} />} title="Quick command suite" detail="Injected into the running container stdin" /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Clear server lag', '/kill @e[type=item]'], ['Force world save', '/save-all flush'], ['Reload permissions', 'lp reload'], ['Toggle whitelist', 'whitelist toggle']].map(([label, command]) => <button key={label} onClick={() => notify(`${command} sent`)} className="quick-action">{label}<small>{command}</small></button>)}</div></section></>; }
function SettingsPage({ server, notify }) { const [confirm, setConfirm] = useState(''); return <><PageHeading title="Settings & SFTP" description="Technical identifiers and destructive server controls." /><section className="panel p-5"><PanelHeader icon={<KeyRound size={17} />} title="Technical identifiers" detail="Use these values for SFTP and integrations" /><div className="mt-5 grid gap-4 sm:grid-cols-2 text-sm"><StatusRow label="UUID" value={server.uuid || 'local-demo'} /><StatusRow label="Docker container" value={server.container_name || 'not provisioned'} /><StatusRow label="SFTP host" value="127.0.0.1" /><StatusRow label="SFTP port" value="2022" /><StatusRow label="SFTP username" value={`server-${server.id || 1}`} /></div></section><section className="mt-6 rounded-xl border border-rose-500/30 bg-rose-500/5 p-5"><h3 className="font-semibold text-rose-300">Danger zone</h3><p className="mt-2 text-sm text-slate-400">Reinstall or wipe requires explicit confirmation and stops the container first.</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => notify('Reinstall queued')} className="button-secondary border-amber-500/40 text-amber-300"><RefreshCw size={14} /> Reinstall</button><input className="field max-w-xs" placeholder="Type server name to wipe" value={confirm} onChange={(event) => setConfirm(event.target.value)} /><button disabled={!confirm} onClick={() => notify('Wipe request blocked pending backend confirmation')} className="button-secondary border-rose-500/40 text-rose-300 disabled:opacity-40"><Trash2 size={14} /> Wipe</button></div></section></>; }
